{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.applicationName }} 
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.fromNamespace }}
      podSelector:
        matchLabels:
          app: {{ .Values.networkPolicy.allowedPodLabel }}
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.dbPort }}
{{- end -}}