apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-quota
  namespace: {{ .Values.namespace | default "db-space" }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.hard.cpu.requests }}     
    requests.memory: {{ .Values.quota.hard.memory.requests }}    
    limits.cpu: {{ .Values.quota.hard.cpu.limits }}           
    limits.memory: {{ .Values.quota.hard.memory.limits }}      
    pods: {{ .Values.quota.hard.pods }}
    persistentvolumeclaims: {{ .Values.quota.hard.volumes.claims }}
    requests.storage: {{ .Values.quota.hard.volumes.storage }}