apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-quota
  namespace: {{ .Values.namespace | default "db-space" }}
spec:
  hard:
    requests.cpu: "1500m"      
    requests.memory: "2Gi"    
    limits.cpu: "2"           
    limits.memory: "3Gi"      
    pods: "3"
    persistentvolumeclaims: "2"
    requests.storage: "5Gi"