apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace | default "db-space" }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.password | b64enc | quote }}