apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-service
  namespace: {{ .Values.namespace | default "db-space" }}
spec:
  type: ClusterIP 
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.dbPort }}       
      targetPort: {{ .Values.networkPolicy.dbPort }} 