apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "app-space" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - name: {{ .Values.applicationName }}
        livenessProbe:
          httpGet:
            path: {{ .Values.connectivity.rootPath }}
            port: {{ .Values.connectivity.applicationPort }}
          initialDelaySeconds: {{ .Values.probesIntervalsSeconds.liveness.initialDelay }} 
          periodSeconds: {{ .Values.probesIntervalsSeconds.liveness.period }} 
        readinessProbe:
          httpGet:
            path: {{ .Values.connectivity.rootPath }}
            port: {{ .Values.connectivity.applicationPort }}
          initialDelaySeconds: {{ .Values.probesIntervalsSeconds.readiness.initialDelay }}
          periodSeconds: {{ .Values.probesIntervalsSeconds.readiness.period }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu}}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.connectivity.applicationPort }}
        env:
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_USER
          value: {{ .Values.database.user | quote }}
        - name: DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secret
              key: db-password