apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa 
  namespace: {{ .Values.namespace | default "app-space" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }} 
  minReplicas: {{ .Values.hpa.replicas.minRep }}
  maxReplicas: {{ .Values.hpa.replicas.maxRep }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.resource.name }}
      target:
        type: {{ .Values.hpa.resource.type }}
        averageUtilization: {{ .Values.hpa.resource.use }}