apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  namespace: app-space
spec:
  type: ClusterIP
  selector:
    app: hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 