apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  namespace: app-space
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.connectivity.applicationPort }}