replicaCount: 2
namespace: app-space
image:
  repository: hello-api
  tag: v1
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits: 
    memory: "256Mi"
    cpu: "500m"

database:
  host: "postgres-service.db-space.svc.cluster.local"
  user: "postgres"
  name: "hello_db"
  password: "password"

ingress:
  enabled: true
  host: hello-world.local