replicaCount: 2
namespace: app-space
applicationName: hello-api
image:
  repository: hello-api
  tag: v1
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits: 
    memory: "256Mi"
    cpu: "500m"

database:
  host: "postgres-service.db-space.svc.cluster.local"
  user: "postgres"
  name: "hello_db"
  password: "password"

ingress:
  enabled: true
  host: hello-world.local
  path: "/"
  port: "80"

connectivity:
  rootPath: "/"
  applicationPort: "8000"

probesIntervalsSeconds:
  readiness:
    initialDelay: "5"
    period: "5"

  liveness:  
    initialDelay: "10"
    period: "10"

hpa:
  replicas:
    minRep: "2"
    maxRep: "10"
  resource:
    name: "cpu"
    type: "Utilization"
    use: "50"

quota:
  hard:
    cpu:
      requests: "1"
      limits: "2"
    memory:
      requests: "1Gi"
      limits: "2Gi"     
    pods: "10"  
